spring:
  application:
    name: User-Profile
  datasource:
    url: jdbc:mysql://localhost:3306/user_profile
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka


