spring:
  application:
    name: User-Profile

  datasource:
    url: jdbc:mysql://localhost:3306/user_profile
#    url: jdbc:mysql://mysql-db3:3306/user_profile
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  cache:
    type: redis
    cache-names:
      - cache1
      - cache2
    redis:
      time-to-live: 6000

  redis:
    host: redis-service
    port: 6379


server:
  port: 8082

#eureka:
#  client:
#    serviceUrl:
##      defaultZone: http://naming-server-service:8761/eureka
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

#Kubernetes

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #      podname-{replica-indes}.{service-name}.default.svc.cluster.local

      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka