spring:
  application:
    name: User-Profile

  datasource:
    url: jdbc:mysql://localhost:3306/user_profile
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  cache:
    type: redis
    cache-names:
      - cache1
      - cache2
    redis:
      time-to-live: 6000

  redis:
    host: localhost
    port: 6379


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka


